# Generated by Django 3.2.7 on 2021-12-02 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_bookings_room_room_type_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type',
            old_name='room_type',
            new_name='room_type_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeapp.room_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 2, 18, 41, 6, 160460)),
        ),
    ]
