# Generated by Django 3.2.7 on 2021-12-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20211202_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_room_type',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 3, 12, 26, 40, 726046)),
        ),
    ]
