# Generated by Django 3.2.7 on 2021-12-03 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20211203_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 3, 15, 51, 41, 933898)),
        ),
    ]
